version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SITE_NAME=${NEXT_PUBLIC_SITE_NAME}
        - NEXT_PUBLIC_STATIC_URL=${NEXT_PUBLIC_STATIC_URL}
    ports:
      - 3000:3000
    volumes:
      - .env:/app/.env:ro
    depends_on:
      - db

volumes:
  postgres-data:
